import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cookies } from "next/headers";
import AuthProvider from "@/auth/components/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SGD",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const cookieStore = cookies();
  const theme = JSON.parse(cookieStore.get("theme")?.value ?? "light")

  return (
    <AuthProvider>
      <html lang="en">
        <body
          className={`${inter.className} ${theme} dark:text-white dark:bg-black`}
        >
          {children}
        </body>
      </html>
    </AuthProvider>
  );
}
