import type { Metadata } from "next";
import "./globals.css";
import { cookies } from "next/headers";
import { fontSans } from "./config/fonts";
import { cn } from "@/lib/utils";
import { Toaster as SonnarToaster } from "@/components/ui/sonner";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "SGD",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const cookieStore = cookies();
  const theme = cookieStore.get("theme")?.value
    ? JSON.parse(cookieStore.get("theme")!.value)
    : "light";

  return (
    <html lang="en">
      <body
        // className={`${inter.className} ${theme} dark:text-white dark:bg-black`}
        className={cn(
          "min-h-screen bg-background font-sans antialiased dark:text-white dark:bg-black",
          fontSans.variable,
          theme
        )}
      >
        {children}
        <Toaster />
        <SonnarToaster theme={theme} richColors />
      </body>
    </html>
  );
}
